DO $$ DECLARE
    v_route_stage_1 text;
    v_route_stage_2 text;
    v_route_stage_3 text;
    v_route_stage_4 text;
    v_route_stage_5 text;
    v_route_stage_6 text;
    v_route_stage_7 text;
    v_route_stage_8 text;
    v_route_stage_9 text;
BEGIN
    -- ---------------------------------------------------------------------------
    -- Bus Routes (Stages)
    -- ---------------------------------------------------------------------------
    INSERT INTO bus_routes (id, "routeNo", name, "isActive") VALUES
        (gen_random_uuid()::text, 'STAGE_1', 'Stage 1', TRUE),
        (gen_random_uuid()::text, 'STAGE_2', 'Stage 2', TRUE),
        (gen_random_uuid()::text, 'STAGE_3', 'Stage 3', TRUE),
        (gen_random_uuid()::text, 'STAGE_4', 'Stage 4', TRUE),
        (gen_random_uuid()::text, 'STAGE_5', 'Stage 5', TRUE),
        (gen_random_uuid()::text, 'STAGE_6', 'Stage 6', TRUE),
        (gen_random_uuid()::text, 'STAGE_7', 'Stage 7', TRUE),
        (gen_random_uuid()::text, 'STAGE_8', 'Stage 8', TRUE),
        (gen_random_uuid()::text, 'STAGE_9', 'Stage 9', TRUE)
    ON CONFLICT DO NOTHING;

    -- Fetch route IDs into variables so we can link stops
    SELECT id INTO v_route_stage_1 FROM bus_routes WHERE "routeNo" = 'STAGE_1' LIMIT 1;
    SELECT id INTO v_route_stage_2 FROM bus_routes WHERE "routeNo" = 'STAGE_2' LIMIT 1;
    SELECT id INTO v_route_stage_3 FROM bus_routes WHERE "routeNo" = 'STAGE_3' LIMIT 1;
    SELECT id INTO v_route_stage_4 FROM bus_routes WHERE "routeNo" = 'STAGE_4' LIMIT 1;
    SELECT id INTO v_route_stage_5 FROM bus_routes WHERE "routeNo" = 'STAGE_5' LIMIT 1;
    SELECT id INTO v_route_stage_6 FROM bus_routes WHERE "routeNo" = 'STAGE_6' LIMIT 1;
    SELECT id INTO v_route_stage_7 FROM bus_routes WHERE "routeNo" = 'STAGE_7' LIMIT 1;
    SELECT id INTO v_route_stage_8 FROM bus_routes WHERE "routeNo" = 'STAGE_8' LIMIT 1;
    SELECT id INTO v_route_stage_9 FROM bus_routes WHERE "routeNo" = 'STAGE_9' LIMIT 1;

    -- Bus Stops
    INSERT INTO bus_stops (id, "routeId", "stopName", stage, distance) VALUES
        (gen_random_uuid()::text, v_route_stage_1, '1 லட்சுமி நகர்', '1', '1.74'),
        (gen_random_uuid()::text, v_route_stage_1, '1 ஸ்ரீமஹால்', '1', '1.66'),
        (gen_random_uuid()::text, v_route_stage_1, '1 தோட்டக்காடு', '1', '1.91'),
        (gen_random_uuid()::text, v_route_stage_1, '1 மாடர்ன்வேபிரிட்ஜ்', '1', '1.73'),
        (gen_random_uuid()::text, v_route_stage_1, '1 மடத்தூர்', '1', '1.99'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம் அரசுப்பள்ளி-2', '1', '1.93'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம் அரசுப்பள்ளி-1', '1', '1.93'),
        (gen_random_uuid()::text, v_route_stage_1, '1 சிமெண்ட் கடை', '1', '1.79'),
        (gen_random_uuid()::text, v_route_stage_1, '1 பச்சாங்காட்டு பிரிவு', '1', '1.74'),
        (gen_random_uuid()::text, v_route_stage_1, '1 காட்டூர்-6', '1', '2'),
        (gen_random_uuid()::text, v_route_stage_1, '1 காட்டூர்-7', '1', '1.7'),
        (gen_random_uuid()::text, v_route_stage_1, '1 காட்டூர்-8', '1', '1.2'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம்-மொரம்புக்காடு-1', '1', '1.8'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம்-மொரம்புக்காடு-2', '1', '1.7'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம்-மொரம்புக்காடு-3', '1', '1.6'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம்-ஸ்டேட் பேங்க்', '1', '1.2'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம் பேக்கரி', '1', '1'),
        (gen_random_uuid()::text, v_route_stage_1, '1 மேட்டுக்காடு டேங்க்', '1', '1.92'),
        (gen_random_uuid()::text, v_route_stage_1, '1 குண்டுருசம்பாளையம்', '1', '1.19'),
        (gen_random_uuid()::text, v_route_stage_1, '1 எண்ணெய் மண்டி-2', '1', '1.76'),
        (gen_random_uuid()::text, v_route_stage_1, '1 பைபாஸ்-1', '1', '1.85'),
        (gen_random_uuid()::text, v_route_stage_1, '1 பைபாஸ்-2', '1', '1.85'),
        (gen_random_uuid()::text, v_route_stage_1, '1 பைபாஸ்-3', '1', '1.85'),
        (gen_random_uuid()::text, v_route_stage_1, '1 பைபாஸ்-4', '1', '1.85'),
        (gen_random_uuid()::text, v_route_stage_1, '1 வைகுந்தம் ரோடு', '1', '1.59'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம் பஸ் ஸ்டாப்-1', '1', '1.28'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம் பஸ் ஸ்டாப்-2', '1', '1.28'),
        (gen_random_uuid()::text, v_route_stage_1, '1 சாந்தி சில்க் ஹவுஸ்', '1', '1.07'),
        (gen_random_uuid()::text, v_route_stage_1, '1 ரெங்கபாளையம்-1', '1', '1.02'),
        (gen_random_uuid()::text, v_route_stage_1, '1 ரெங்கபாளையம்-2', '1', '1.02'),
        (gen_random_uuid()::text, v_route_stage_1, '1 ரங்கம்பாளையம்-1', '1', '1.23'),
        (gen_random_uuid()::text, v_route_stage_1, '1 ரங்கம்பாளையம்-2', '1', '1.05'),
        (gen_random_uuid()::text, v_route_stage_1, '1 ரங்கம்பாளையம்-3', '1', '1.02'),
        (gen_random_uuid()::text, v_route_stage_1, '1 மோரி வளவு', '1', '1.23'),
        (gen_random_uuid()::text, v_route_stage_1, '1 பாலாஜி பர்னிச்சர்', '1', '1.54'),
        (gen_random_uuid()::text, v_route_stage_1, '1 ரெட்டிப்பட்டி பார்க்', '1', '1.78'),
        (gen_random_uuid()::text, v_route_stage_1, '1 ரெட்டிப்பட்டி', '1', '1.78'),
        (gen_random_uuid()::text, v_route_stage_1, '1 வைகுந்தம் பிரிவு ரோடு', '1', '1.69'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம்-அரசுப்பள்ளி-1', '1', '1.98'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம்-அரசுப்பள்ளி-2', '1', '1.98'),
        (gen_random_uuid()::text, v_route_stage_1, '1 ரங்கம்பாளையம்', '1', '1'),
        (gen_random_uuid()::text, v_route_stage_1, '1 பெரிய மாரியம்மன் கோவில் பிரிவு', '1', '1.45'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கே.எஸ்.நகர்-1', '1', '1.71'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கே.எஸ்.நகர்-2', '1', '1.65'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம் காவல் நிலையம்', '1', '1.65'),
        (gen_random_uuid()::text, v_route_stage_1, '1 பச்சாங்காடு பிரிவு', '1', '1.72'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம் அரசு பள்ளி', '1', '1.98'),
        (gen_random_uuid()::text, v_route_stage_1, '1 கொங்கணாபுரம்', '1', '1.31'),
        (gen_random_uuid()::text, v_route_stage_1, '1 சின்ன மாரியம்மன் கோவில்', '1', '1.45'),
        (gen_random_uuid()::text, v_route_stage_1, '1 குண்டரசம்பாளையம்', '1', '0.4'),
        (gen_random_uuid()::text, v_route_stage_1, '1 குண்டரசம்பாளையம் முள்ளிக்காடு', '1', '0.4'),
        (gen_random_uuid()::text, v_route_stage_1, '1 மோரிவளவு', '1', '1'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஸ்ரீஅம்மன் நகர் பருத்தி மில்', '2', '3.4'),
        (gen_random_uuid()::text, v_route_stage_2, '2 மட்டம்பட்டி', '2', '3.58'),
        (gen_random_uuid()::text, v_route_stage_2, '2 வேல்முருகன் மில்', '2', '3.55'),
        (gen_random_uuid()::text, v_route_stage_2, '2 எருமைப்பட்டி பிரிவு', '2', '3.55'),
        (gen_random_uuid()::text, v_route_stage_2, '2 முத்துசாமி மில்', '2', '3.75'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஒடுவங்காட்டுவளவு', '2', '3.8'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஆனைக்காட்டூர்தென்னைமரம்', '2', '2.72'),
        (gen_random_uuid()::text, v_route_stage_2, '2 கட்டியனூர்', '2', '2.88'),
        (gen_random_uuid()::text, v_route_stage_2, '2 கோரக்குட்டப்பட்டி', '2', '3.32'),
        (gen_random_uuid()::text, v_route_stage_2, '2 அய்யம்பாளையம்', '2', '3.66'),
        (gen_random_uuid()::text, v_route_stage_2, '2 தொண்டிபாளையம்', '2', '3.95'),
        (gen_random_uuid()::text, v_route_stage_2, '2 மசக்குமாரபாளையம்', '2', '3.75'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஆயில் மில்', '2', '2.82'),
        (gen_random_uuid()::text, v_route_stage_2, '2 வெள்ளக்கல்பட்டி-1', '2', '3.85'),
        (gen_random_uuid()::text, v_route_stage_2, '2 வெள்ளக்கல்பட்டி-2', '2', '3.97'),
        (gen_random_uuid()::text, v_route_stage_2, '2 வெள்ளக்கல்பட்டி பால் சென்டர்', '2', '3.81'),
        (gen_random_uuid()::text, v_route_stage_2, '2 மாரியம்மன் கோவில்-1', '2', '3.97'),
        (gen_random_uuid()::text, v_route_stage_2, '2 மாரியம்மன் கோவில்-2', '2', '3.97'),
        (gen_random_uuid()::text, v_route_stage_2, '2 வெட்டுக்காடு', '2', '2.5'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஆசாரி பட்டறை', '2', '4'),
        (gen_random_uuid()::text, v_route_stage_2, '2 அலகாபாத்வங்கி', '2', '3.74'),
        (gen_random_uuid()::text, v_route_stage_2, '2 சுண்ணாம்புசூலை', '2', '3.64'),
        (gen_random_uuid()::text, v_route_stage_2, '2 நத்தக்காட்டூர்-1', '2', '3.41'),
        (gen_random_uuid()::text, v_route_stage_2, '2 நத்தக்காட்டூர்-2', '2', '2.99'),
        (gen_random_uuid()::text, v_route_stage_2, '2 காட்டுவளவு', '2', '2.14'),
        (gen_random_uuid()::text, v_route_stage_2, '2 செக்காங்காடு-3', '2', '3.52'),
        (gen_random_uuid()::text, v_route_stage_2, '2 செக்காங்காடு-2', '2', '3.63'),
        (gen_random_uuid()::text, v_route_stage_2, '2 செக்காங்காடு-1', '2', '3.82'),
        (gen_random_uuid()::text, v_route_stage_2, '2 எருமைப்பட்டி ஊராட்சிநிலையம்', '2', '3.15'),
        (gen_random_uuid()::text, v_route_stage_2, '2 காவடிக்காரனூர் கோவில்', '2', '3.8'),
        (gen_random_uuid()::text, v_route_stage_2, '2 சேலத்தான்காடு-1', '2', '3.5'),
        (gen_random_uuid()::text, v_route_stage_2, '2 சேலத்தான்காடு-2', '2', '3.2'),
        (gen_random_uuid()::text, v_route_stage_2, '2 சேலத்தான்காடு-3', '2', '3.2'),
        (gen_random_uuid()::text, v_route_stage_2, '2 காட்டூர்-1', '2', '2.7'),
        (gen_random_uuid()::text, v_route_stage_2, '2 காட்டூர்-2', '2', '2.3'),
        (gen_random_uuid()::text, v_route_stage_2, '2 காட்டூர்-3', '2', '2.1'),
        (gen_random_uuid()::text, v_route_stage_2, '2 காட்டூர்-4', '2', '2'),
        (gen_random_uuid()::text, v_route_stage_2, '2 காட்டூர்-5', '2', '2.2'),
        (gen_random_uuid()::text, v_route_stage_2, '2 கொங்கணாபுரம்-குமரன்நகர்-2', '2', '2.2'),
        (gen_random_uuid()::text, v_route_stage_2, '2 கொங்கணாபுரம்-குமரன்நகர்-3', '2', '2.1'),
        (gen_random_uuid()::text, v_route_stage_2, '2 கல்கி கேஸ்குடோன்-1', '2', '3.24'),
        (gen_random_uuid()::text, v_route_stage_2, '2 கல்கி கேஸ்குடோன்-2', '2', '3.24'),
        (gen_random_uuid()::text, v_route_stage_2, '2 எட்டிமரத்தான் காடு', '2', '2.37'),
        (gen_random_uuid()::text, v_route_stage_2, '2 கெங்குப்பட்டி-1', '2', '2.61'),
        (gen_random_uuid()::text, v_route_stage_2, '2 குறிக்கியான் காடு', '2', '2.51'),
        (gen_random_uuid()::text, v_route_stage_2, '2 தூங்கானூர்-1', '2', '3.29'),
        (gen_random_uuid()::text, v_route_stage_2, '2 தூங்கானூர்-2', '2', '2.84'),
        (gen_random_uuid()::text, v_route_stage_2, '2 தூங்கானூர்-3', '2', '2.84'),
        (gen_random_uuid()::text, v_route_stage_2, '2 வெட்டுக்காடு ஈ.பி.ஆர்', '2', '3.97'),
        (gen_random_uuid()::text, v_route_stage_2, '2 வெட்டுக்காடு பால்சென்டர்', '2', '3.95'),
        (gen_random_uuid()::text, v_route_stage_2, '2 வெட்டுக்காடு பஸ்ஸ்டாப்', '2', '3.56'),
        (gen_random_uuid()::text, v_route_stage_2, '2 கூலையங்காடு', '2', '3.04'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஆன்றபட்டியான்காடு -1', '2', '2.22'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஆன்றபட்டியான்காடு - 2', '2', '2.22'),
        (gen_random_uuid()::text, v_route_stage_2, '2 பழனியாங்காடு', '2', '2.86'),
        (gen_random_uuid()::text, v_route_stage_2, '2 கடவளவு', '2', '2.64'),
        (gen_random_uuid()::text, v_route_stage_2, '2 கீழ்க்கூத்தாடிபாளையம்', '2', '3.55'),
        (gen_random_uuid()::text, v_route_stage_2, '2 தூங்கானூர்', '2', '2.91'),
        (gen_random_uuid()::text, v_route_stage_2, '2 புதுக்காடு', '2', '2.31'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஆணைக்காடு மாரியம்மன் கோவில்', '2', '2.53'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஆனைக்காடு', '2', '2.86'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஐயம்பாளையம்', '2', '3.67'),
        (gen_random_uuid()::text, v_route_stage_2, '2 மூலப்பாதை-1', '2', '3.85'),
        (gen_random_uuid()::text, v_route_stage_2, '2 மூலப்பாதை-2', '2', '3.75'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஆசாரிப்பட்டறை-1', '2', '2.84'),
        (gen_random_uuid()::text, v_route_stage_2, '2 ஆசாரிப்பட்டறை-2', '2', '2.84'),
        (gen_random_uuid()::text, v_route_stage_2, '2 குமரன் நகர்-1', '2', '2.52'),
        (gen_random_uuid()::text, v_route_stage_2, '2 மொரம்புக்காடு - 1', '2', '2.27'),
        (gen_random_uuid()::text, v_route_stage_2, '2 பாலிபெருமாள்கோவில்-1', '2', '4'),
        (gen_random_uuid()::text, v_route_stage_2, '2 பாலிபெருமாள்கோவில் - 2', '2', '4'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பூவானூர் பங்க்', '3', '5.6'),
        (gen_random_uuid()::text, v_route_stage_3, '3 ஜோசியர்காடு', '3', '4.8'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கன்னந்தேரி-1', '3', '4.6'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கன்னந்தேரி-2', '3', '4.11'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கன்னந்தேரி-3', '3', '4.44'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கன்னந்தேரி-4', '3', '4.36'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கன்னந்தேரி-5', '3', '4.22'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பாலிக்காடு', '3', '5.5'),
        (gen_random_uuid()::text, v_route_stage_3, '3 நாயக்கன் வளவு பிரிவு', '3', '5.3'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கூத்தாடிபாளையம் (மேலே-1)', '3', '5.15'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கூத்தாடிபாளையம்', '3', '4.3'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கூத்தாடிபாளையம் (பஸ் ஸ்டாப்)', '3', '4.3'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பாலப்பட்டி பிரிவு', '3', '4.2'),
        (gen_random_uuid()::text, v_route_stage_3, '3 எருமைப்பட்டி பிரிவு', '3', '4.18'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கீழ்கூத்தாடிபாளையம்', '3', '4.1'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பூசாரி காட்டுவளவு-1', '3', '5.21'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பூசாரி காட்டுவளவு-2', '3', '5.37'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பூசாரி காட்டுவளவு-3', '3', '5.61'),
        (gen_random_uuid()::text, v_route_stage_3, '3 தெற்கு வளவு', '3', '5.13'),
        (gen_random_uuid()::text, v_route_stage_3, '3 மேட்டுக்காடு', '3', '4.27'),
        (gen_random_uuid()::text, v_route_stage_3, '3 அப்புசாமி மில்', '3', '4.21'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பூங்கா நகர்', '3', '4.35'),
        (gen_random_uuid()::text, v_route_stage_3, '3 வீரப்பம்பாளையம் ரிங்ரோடு', '3', '5.42'),
        (gen_random_uuid()::text, v_route_stage_3, '3 SRS பால்பண்ணை', '3', '5.76'),
        (gen_random_uuid()::text, v_route_stage_3, '3 வெல்லுத்து பெருமாள் கோவில்', '3', '5.88'),
        (gen_random_uuid()::text, v_route_stage_3, '3 வீரப்பம்பாளையம்', '3', '5.45'),
        (gen_random_uuid()::text, v_route_stage_3, '3 வீரப்பம்பாளையம்-1', '3', '5.45'),
        (gen_random_uuid()::text, v_route_stage_3, '3 புதூர்-1', '3', '4.35'),
        (gen_random_uuid()::text, v_route_stage_3, '3 புதூர்-2', '3', '4.35'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பரையங்காடு வளவு', '3', '5.85'),
        (gen_random_uuid()::text, v_route_stage_3, '3 எருமைப்பட்டி-1', '3', '5.28'),
        (gen_random_uuid()::text, v_route_stage_3, '3 எருமைப்பட்டி-2', '3', '4.92'),
        (gen_random_uuid()::text, v_route_stage_3, '3 எருமைப்பட்டி-3', '3', '4.87'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கூத்தாடிபாளையம்-1', '3', '4.24'),
        (gen_random_uuid()::text, v_route_stage_3, '3 ஆலமரம்-1', '3', '5.28'),
        (gen_random_uuid()::text, v_route_stage_3, '3 ஆலமரம்-2', '3', '5.28'),
        (gen_random_uuid()::text, v_route_stage_3, '3 தங்காயூர்', '3', '5.8'),
        (gen_random_uuid()::text, v_route_stage_3, '3 நோட்டக்காரன்குட்டை', '3', '5.3'),
        (gen_random_uuid()::text, v_route_stage_3, '3 தேவனூர்பிரிவு', '3', '4.75'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கருக்கன் காட்டுவளவு', '3', '4.33'),
        (gen_random_uuid()::text, v_route_stage_3, '3 மூலப்பாதை-1', '3', '4.18'),
        (gen_random_uuid()::text, v_route_stage_3, '3 மூலப்பாதை-2', '3', '4.18'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பூவானூர்- 1', '3', '5.64'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பூவானூர்- 2', '3', '5.64'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கச்சுப்பள்ளி-1', '3', '5.04'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கச்சுப்பள்ளி-2', '3', '5.31'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கச்சுப்பள்ளி-3', '3', '5.31'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கச்சுப்பள்ளி பூங்கா', '3', '5.31'),
        (gen_random_uuid()::text, v_route_stage_3, '3 எருமைப்பட்டி தபால்நிலையம்', '3', '4.08'),
        (gen_random_uuid()::text, v_route_stage_3, '3 எருமைப்பட்டி -2', '3', '4.14'),
        (gen_random_uuid()::text, v_route_stage_3, '3 எருமைப்பட்டி -1', '3', '4.63'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பாலப்பட்டி -3', '3', '5.27'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பாலப்பட்டி -2', '3', '5.45'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பாலப்பட்டி -1', '3', '5.77'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பலகாரவலவு', '3', '4.98'),
        (gen_random_uuid()::text, v_route_stage_3, '3 வெள்ளையம்பாளையம்-3', '3', '5.71'),
        (gen_random_uuid()::text, v_route_stage_3, '3 வெள்ளையம்பாளையம்-2', '3', '5.71'),
        (gen_random_uuid()::text, v_route_stage_3, '3 வெள்ளையம்பாளையம்-1', '3', '5.98'),
        (gen_random_uuid()::text, v_route_stage_3, '3 மோட்டூர்', '3', '4.39'),
        (gen_random_uuid()::text, v_route_stage_3, '3 நாச்சனூர்-2', '3', '5.08'),
        (gen_random_uuid()::text, v_route_stage_3, '3 நாச்சனூர்-1', '3', '5.12'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கோரணம்பட்டி-2', '3', '5.68'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கோரணம்பட்டி-1', '3', '5.81'),
        (gen_random_uuid()::text, v_route_stage_3, '3 நாச்சனூர் காட்டுவளவு', '3', '5.76'),
        (gen_random_uuid()::text, v_route_stage_3, '3 சாமுண்டிவளவு', '3', '5.88'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பெரிய நாச்சியூர்', '3', '5.46'),
        (gen_random_uuid()::text, v_route_stage_3, '3 காவடிக்காரனூர் எலந்தக்குட்டை-1', '3', '4.6'),
        (gen_random_uuid()::text, v_route_stage_3, '3 காவடிக்காரனூர் எலந்தக்குட்டை-2', '3', '4.6'),
        (gen_random_uuid()::text, v_route_stage_3, '3 காவடிக்காரனூர் வளவு', '3', '4.2'),
        (gen_random_uuid()::text, v_route_stage_3, '3 காவடிக்காரனூர்-1', '3', '4.6'),
        (gen_random_uuid()::text, v_route_stage_3, '3 காவடிக்காரனூர்-2', '3', '4.6'),
        (gen_random_uuid()::text, v_route_stage_3, '3 காவடிக்காரனூர்-3', '3', '4.4'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பவர் ஆபிஸ்', '3', '4.36'),
        (gen_random_uuid()::text, v_route_stage_3, '3 குரும்பப்பட்டி மாரியம்மன் கோவில்', '3', '4.1'),
        (gen_random_uuid()::text, v_route_stage_3, '3 மூலப்பாதை (மேட்டுக்காடு)', '3', '4.38'),
        (gen_random_uuid()::text, v_route_stage_3, '3 சின்னமணிவளவு', '3', '5.69'),
        (gen_random_uuid()::text, v_route_stage_3, '3 வெண்டனூர்', '3', '4.67'),
        (gen_random_uuid()::text, v_route_stage_3, '3 குரும்பபட்டி பழனி அண்டிகாடு', '3', '4.16'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பெரியநாச்சியூர்', '3', '4.43'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கட்டபுளியங்காடு', '3', '5.35'),
        (gen_random_uuid()::text, v_route_stage_3, '3 முள்ளுக்காடு', '3', '5.68'),
        (gen_random_uuid()::text, v_route_stage_3, '3 துளுக்கங்காடு', '3', '4.4'),
        (gen_random_uuid()::text, v_route_stage_3, '3 சாந்தங்காடு', '3', '4.4'),
        (gen_random_uuid()::text, v_route_stage_3, '3 அம்மன்காட்டூர் பஸ் ஸ்டாப்', '3', '4.09'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கந்தன் நகர்', '3', '4.68'),
        (gen_random_uuid()::text, v_route_stage_3, '3 அம்மன்காட்டூர் மாரியம்மன் கோவில்', '3', '4.68'),
        (gen_random_uuid()::text, v_route_stage_3, '3 அம்மன்காட்டூர் ஊர்', '3', '4.96'),
        (gen_random_uuid()::text, v_route_stage_3, '3 அம்மன்காட்டூர் குரை', '3', '4.94'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கௌரி மெஸ்', '3', '4.51'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பன்னாரி அம்மன்கடை', '3', '4.57'),
        (gen_random_uuid()::text, v_route_stage_3, '3 ஸ்வெலக்ட கம்பனி', '3', '4.64'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கேட்டுக்கடை', '3', '4.82'),
        (gen_random_uuid()::text, v_route_stage_3, '3 வெள்ளாண்டிவலசு', '3', '5.59'),
        (gen_random_uuid()::text, v_route_stage_3, '3 காளியம்மன் கோவில்', '3', '5.81'),
        (gen_random_uuid()::text, v_route_stage_3, '3 சக்தி தியேட்டர்', '3', '5.93'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பெட்ரோல் பங்க்', '3', '5.28'),
        (gen_random_uuid()::text, v_route_stage_3, '3 எருமைப்பட்டி', '3', '4.66'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பாலப்பட்டி', '3', '4.73'),
        (gen_random_uuid()::text, v_route_stage_3, '3 முனியப்பன் கோவில்', '3', '5.34'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கருக்கங்காடு', '3', '5.21'),
        (gen_random_uuid()::text, v_route_stage_3, '3 சந்தோஷ்நகர்', '3', '5.45'),
        (gen_random_uuid()::text, v_route_stage_3, '3 வித்யா காலேஜ்', '3', '4.54'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கச்சுப்பள்ளி', '3', '5.06'),
        (gen_random_uuid()::text, v_route_stage_3, '3 சக்தி மஹால் திருமண மண்டபம்', '3', '5.45'),
        (gen_random_uuid()::text, v_route_stage_3, '3 மசக்காரம்பாளையம்-1', '3', '4.27'),
        (gen_random_uuid()::text, v_route_stage_3, '3 மசக்காரம்பாளையம்-2', '3', '4.27'),
        (gen_random_uuid()::text, v_route_stage_3, '3 மசக்காரம்பாளையம்-3', '3', '4.27'),
        (gen_random_uuid()::text, v_route_stage_3, '3 பூவானூர் பேருந்து நிறுத்தம்', '3', '5.64'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கன்னந்தேரி -1', '3', '4.17'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கன்னந்தேரி -2', '3', '4.17'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கன்னந்தேரி -3', '3', '4.17'),
        (gen_random_uuid()::text, v_route_stage_3, '3 காவடிக்காரனூர் -2', '3', '5.4'),
        (gen_random_uuid()::text, v_route_stage_3, '3 காவடிக்காரனூர் -3', '3', '5.4'),
        (gen_random_uuid()::text, v_route_stage_3, '3 காவடிக்காரனூர் -4', '3', '5.4'),
        (gen_random_uuid()::text, v_route_stage_3, '3 காவடிக்காரனூர் -5', '3', '4.4'),
        (gen_random_uuid()::text, v_route_stage_3, '3 மேல் தங்காயூர்', '3', '5.7 Km'),
        (gen_random_uuid()::text, v_route_stage_3, '3 கீழ் தங்காயூர்', '3', '5.7 Km'),
        (gen_random_uuid()::text, v_route_stage_3, '3 அம்மன்காட்டூர்', '3', '4.8 Km'),
        (gen_random_uuid()::text, v_route_stage_3, '3 வெள்ளக்கல்பட்டி', '3', '5.5 Km'),
        (gen_random_uuid()::text, v_route_stage_4, '4 சுண்டமேட்டூர்-1', '4', '7.9'),
        (gen_random_uuid()::text, v_route_stage_4, '4 சுண்டமேட்டூர்-2', '4', '6.7'),
        (gen_random_uuid()::text, v_route_stage_4, '4 சுண்டமேட்டூர்-3', '4', '6.7'),
        (gen_random_uuid()::text, v_route_stage_4, '4 சுண்டமேட்டூர்-4', '4', '6.6'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஒண்டிபனை-1', '4', '6.5'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஒண்டிபனை-2', '4', '6.5'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஒண்டிபனை-4', '4', '6.4'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஒண்டிகடை-1', '4', '6.15'),
        (gen_random_uuid()::text, v_route_stage_4, '4 குண்டல் பட்டி', '4', '6.6'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பாபி கடை-1', '4', '7.23'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பாபி கடை-3', '4', '7.23'),
        (gen_random_uuid()::text, v_route_stage_4, '4 காட்டூர்-1', '4', '6.63'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கரையானூர்', '4', '9.21'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மாங்குட்டப்பட்டி-1', '4', '7.59'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மாங்குட்டப்பட்டி-2', '4', '7.41'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மாங்குட்டப்பட்டி-3', '4', '7.39'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மாங்குட்டப்பட்டி-4', '4', '7.39'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மாங்குட்டப்பட்டி-5', '4', '7.39'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கொண்டக்கார வளவு-1', '4', '6.64'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கொண்டக்கார வளவு-2', '4', '6.77'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பனங்காட்டூர்-1', '4', '6.25'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பனங்காட்டூர்-2', '4', '6.25'),
        (gen_random_uuid()::text, v_route_stage_4, '4 வரதங்காட்டானூர்', '4', '6.77'),
        (gen_random_uuid()::text, v_route_stage_4, '4 குட்டிபையன் வளவு-1', '4', '7.83'),
        (gen_random_uuid()::text, v_route_stage_4, '4 குட்டிபையன் வளவு-2', '4', '7.83'),
        (gen_random_uuid()::text, v_route_stage_4, '4 முனியப்பன்கோவில்(கோரணம்பட்டி)', '4', '7.24'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஏரிக்காடு', '4', '6.12'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ராயணம்பட்டி பிரிவு', '4', '7.48'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கோம்பைக்காடு', '4', '7.15'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஆண்டிபாளையம்', '4', '6.77'),
        (gen_random_uuid()::text, v_route_stage_4, '4 செட்டியூர்', '4', '6.25'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஒண்டிப்பனை', '4', '7.11'),
        (gen_random_uuid()::text, v_route_stage_4, '4 தண்ணீர் பைப்', '4', '7.15'),
        (gen_random_uuid()::text, v_route_stage_4, '4 அ.புதூர்', '4', '7.86'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கரட்டூர் மாரியம்மன்கோவில்', '4', '7.61'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கரட்டூர்-2', '4', '6.97'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பெருமாள் கோவில்', '4', '7.28'),
        (gen_random_uuid()::text, v_route_stage_4, '4 காட்டூர்-2', '4', '6.97'),
        (gen_random_uuid()::text, v_route_stage_4, '4 காட்டூர்-3', '4', '6.97'),
        (gen_random_uuid()::text, v_route_stage_4, '4 காட்டூர்-4', '4', '6.62'),
        (gen_random_uuid()::text, v_route_stage_4, '4 காட்டூர்-5', '4', '6.62'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஒண்டிக்கடை-1', '4', '6.37'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஒண்டிக்கடை-2', '4', '6.37'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கோசேரிப்பட்டி-1', '4', '6.86'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கோசேரிப்பட்டி-2', '4', '6.86'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கோசேரிப்பட்டி-3', '4', '6.86'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கருப்பாய்காடு', '4', '6.54'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பள்ளிப்பட்டி', '4', '6.85'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பள்ளிப்பட்டி-பிரிவு', '4', '6.38'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கல்லங்காடு', '4', '7.82'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கோவலங்காடு பிள்ளையார் கோவில்-1', '4', '7.8'),
        (gen_random_uuid()::text, v_route_stage_4, '4 தெற்குகாடு-1', '4', '6.91'),
        (gen_random_uuid()::text, v_route_stage_4, '4 தெற்குகாடு', '4', '6.91'),
        (gen_random_uuid()::text, v_route_stage_4, '4 தெற்குகாடு-2', '4', '6.91'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கோவலங்காடு கொடிகம்பம்', '4', '6.11'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மூலக்கடை-2', '4', '6.37'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மூலக்கடை-1', '4', '6.45'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கரட்டுக்காடு-2', '4', '6.71'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கரட்டுக்காடு-1', '4', '6.71'),
        (gen_random_uuid()::text, v_route_stage_4, '4 செல்லியம்மன்கோவில் மோரி-2', '4', '7.76'),
        (gen_random_uuid()::text, v_route_stage_4, '4 செல்லியம்மன்கோவில் மோரி-1', '4', '7.76'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஆசாரிகாடு-2', '4', '6.02'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஆசாரிகாடு-1', '4', '6.02'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பனங்காடு', '4', '6.04'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பட்டரை காட்டு வளவு', '4', '7.57'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பக்கரிக்காட்டு வளவு', '4', '7.66'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பள்ளிப்பட்டி பிரிவு', '4', '6.13'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஸ்டேட் பேங்க்', '4', '7.72'),
        (gen_random_uuid()::text, v_route_stage_4, '4 போலீஸ் குவார்ட்டர்ஸ்', '4', '7.76'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மாட்டு ஹாஸ்பிட்டல்', '4', '7.61'),
        (gen_random_uuid()::text, v_route_stage_4, '4 வைத்தியலிங்கம் திருமணமண்டபம்', '4', '7.43'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பத்திரஆபிஸ்-1', '4', '7.27'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பத்திரஆபிஸ்-2', '4', '7.27'),
        (gen_random_uuid()::text, v_route_stage_4, '4 போலீஸ் ஸ்டேசன்', '4', '7.15'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கும்பகோணம் பாத்திரக்கடை-1', '4', '7.89'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கும்பகோணம் பாத்திரக்கடை-2', '4', '7.89'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மோகன் ஹாஸ்பிட்டல்', '4', '7.81'),
        (gen_random_uuid()::text, v_route_stage_4, '4 Y.V.B சில்க்ஸ்-1', '4', '7.72'),
        (gen_random_uuid()::text, v_route_stage_4, '4 Y.V.B சில்க்ஸ்-2', '4', '7.72'),
        (gen_random_uuid()::text, v_route_stage_4, '4 S.K.பல் மருத்துவமனை', '4', '7.67'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மேட்டுத்தெரு', '4', '7.55'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கோகிலா மெடிக்கல்', '4', '7.46'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கோகுலகிருஷ்ணன் மருத்துவமனை', '4', '7.36'),
        (gen_random_uuid()::text, v_route_stage_4, '4 அங்காளம்மன் கோவில் தெரு-1', '4', '7.25'),
        (gen_random_uuid()::text, v_route_stage_4, '4 அங்காளம்மன் கோவில் தெரு-2', '4', '7.25'),
        (gen_random_uuid()::text, v_route_stage_4, '4 திரௌபதி அம்மன்கோவில்', '4', '7.14'),
        (gen_random_uuid()::text, v_route_stage_4, '4 யூனியன் ஆபிஸ்', '4', '6.33'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பாவா மெடிக்கல்', '4', '6.79'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மோட்டூர்-1', '4', '6.11'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மோட்டூர்-2', '4', '6.11'),
        (gen_random_uuid()::text, v_route_stage_4, '4 வாழக்குட்டைப்பட்டி', '4', '7.18'),
        (gen_random_uuid()::text, v_route_stage_4, '4 வாழக்குட்டைப்பட்டி-1', '4', '7.18'),
        (gen_random_uuid()::text, v_route_stage_4, '4 சின்னமணிவளவு பால் சொசைட்டி', '4', '7.04'),
        (gen_random_uuid()::text, v_route_stage_4, '4 தளவாய்ப்பட்டி', '4', '6.11'),
        (gen_random_uuid()::text, v_route_stage_4, '4 தங்காயூர் மாரியம்மன்கோவில்', '4', '7.33'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பரையங்காட்டானூர்', '4', '7.88'),
        (gen_random_uuid()::text, v_route_stage_4, '4 தங்காயூர் மேல்கடை', '4', '6.76'),
        (gen_random_uuid()::text, v_route_stage_4, '4 தங்காயூர்கீழ்கடை', '4', '6.76'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மாமரத்தானூர்', '4', '6.17'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஊஞ்சான்காடு-1', '4', '6.4'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஊஞ்சான்காடு-2', '4', '6.4'),
        (gen_random_uuid()::text, v_route_stage_4, '4 எடப்பாடி-குமரன் தியேட்டர்', '4', '7.58'),
        (gen_random_uuid()::text, v_route_stage_4, '4 செல்லாண்டிஅம்மன் கோவில் தெரு', '4', '7.36'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கவுண்டம்பட்டி', '4', '7.69'),
        (gen_random_uuid()::text, v_route_stage_4, '4 BSNL ஆபிஸ்', '4', '7.31'),
        (gen_random_uuid()::text, v_route_stage_4, '4 சிங்காரவேல் கடை', '4', '7.23'),
        (gen_random_uuid()::text, v_route_stage_4, '4 KRS ஹாஸ்பிட்டல்', '4', '6.06'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கல்கிகேஸ் ஆபிஸ்', '4', '6.16'),
        (gen_random_uuid()::text, v_route_stage_4, '4 எடப்பாடி அரசு ஆண்கள் பள்ளி', '4', '6.62'),
        (gen_random_uuid()::text, v_route_stage_4, '4 தொப்பக்காடு-2', '4', '7.91'),
        (gen_random_uuid()::text, v_route_stage_4, '4 தொப்பக்காடு-1', '4', '7.91'),
        (gen_random_uuid()::text, v_route_stage_4, '4 எட்டிகுட்டைமேடு', '4', '7.94'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கள்ளங்காடு', '4', '7.73'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கொல்லப்பட்டி நிறுத்தம்-1', '4', '6.25'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கொல்லப்பட்டி நிறுத்தம்-2', '4', '6.02'),
        (gen_random_uuid()::text, v_route_stage_4, '4 குண்டல்பட்டி பழையபால் சொசைட்டி', '4', '6.56'),
        (gen_random_uuid()::text, v_route_stage_4, '4 குமரகுரு ரைஸ்மில்', '4', '6.94'),
        (gen_random_uuid()::text, v_route_stage_4, '4 குண்டல்பட்டி', '4', '6.91'),
        (gen_random_uuid()::text, v_route_stage_4, '4 செல்லியம்மன் கோவில்', '4', '7.74'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பள்ளிப்பட்டி-2', '4', '7.58'),
        (gen_random_uuid()::text, v_route_stage_4, '4 எலந்தமரத்தான் காடு', '4', '7.32'),
        (gen_random_uuid()::text, v_route_stage_4, '4 புது ஏரிக்காடு-1', '4', '6.52'),
        (gen_random_uuid()::text, v_route_stage_4, '4 புது ஏரிக்காடு-2', '4', '6.76'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஏ.டி.சி. டிப்போ-1', '4', '7.58'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மேட்டுத்தெரு-1', '4', '7.43'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மேட்டுத்தெரு-2', '4', '7.34'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மேட்டுத்தெரு-3', '4', '7.12'),
        (gen_random_uuid()::text, v_route_stage_4, '4 எடப்பாடி பஸ்நிலையம்', '4', '7.09'),
        (gen_random_uuid()::text, v_route_stage_4, '4 சாணாரப்பட்டி', '4', '6.38'),
        (gen_random_uuid()::text, v_route_stage_4, '4 சின்னமுனியன் வளவு', '4', '7.04'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மோட்டூர்-3', '4', '6.11'),
        (gen_random_uuid()::text, v_route_stage_4, '4 வாழக்குட்டைப்பட்டி-3', '4', '7.18'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கவுண்டம்பட்டி-1', '4', '7.69'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கவுண்டம்பட்டி-2', '4', '7.69'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கவுண்டம்பட்டி-3', '4', '7.69'),
        (gen_random_uuid()::text, v_route_stage_4, '4 குப்பதாசன்வளவு', '4', NULL),
        (gen_random_uuid()::text, v_route_stage_4, '4 குமரன் தியேட்டர்', '4', '7.61'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பிஎஸ்என்எல் ஆபிஸ்-1', '4', '7.31'),
        (gen_random_uuid()::text, v_route_stage_4, '4 பிஎஸ்என்எல் ஆபிஸ்-2', '4', '7.31'),
        (gen_random_uuid()::text, v_route_stage_4, '4 மோட்டூர் காட்டு வளவு', '4', '9.58'),
        (gen_random_uuid()::text, v_route_stage_4, '4 வடக்காடு', '4', NULL),
        (gen_random_uuid()::text, v_route_stage_4, '4 சுண்டமேட்டூர்', '4', '6.07'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ஒண்டிக்கடை', '4', '6.15'),
        (gen_random_uuid()::text, v_route_stage_4, '4 வக்கீல்தோட்டம்', '4', '6.31'),
        (gen_random_uuid()::text, v_route_stage_4, '4 இடைப்பாடி SBI வங்கி', '4', '7'),
        (gen_random_uuid()::text, v_route_stage_4, '4 இடைப்பாடி காவலர் குடியிருப்பு', '4', '6.9'),
        (gen_random_uuid()::text, v_route_stage_4, '4 இடைப்பாடி கால்நடை மருத்துவமனை', '4', '6.9'),
        (gen_random_uuid()::text, v_route_stage_4, '4 இடைப்பாடி காவல் நிலையம்', '4', '6.9'),
        (gen_random_uuid()::text, v_route_stage_4, '4 இடைப்பாடி பேருந்து நிலையம்', '4', '6.8'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கோதாரண்காடு', '4', '7.9'),
        (gen_random_uuid()::text, v_route_stage_4, '4 ராமகிருஷ்ணா மண்டபம்', '4', '7.4 Km'),
        (gen_random_uuid()::text, v_route_stage_4, '4 SP கண் மருத்துவமனை', '4', '7.4 Km'),
        (gen_random_uuid()::text, v_route_stage_4, '4 விஸ்டம் பள்ளி', '4', '7.2 Km'),
        (gen_random_uuid()::text, v_route_stage_4, '4 காளியம்மன் கோவில்', '4', '7 Km'),
        (gen_random_uuid()::text, v_route_stage_4, '4 கும்பகோண பாத்திரக்கடை', '4', '7 Km'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகனூர்-1', '5', '9.5'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகனூர்-2', '5', '9.5'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகனூர் -3', '5', '9.4'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகனூர் -4', '5', '9.4'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஆசாரிபட்டரை-1', '5', '9.2'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அண்ணாநகர்-1', '5', '8.9'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அண்ணாநகர் -2', '5', '8.9'),
        (gen_random_uuid()::text, v_route_stage_5, '5 செல்லியம்மன் கோவில் மோரி', '5', '8.71'),
        (gen_random_uuid()::text, v_route_stage_5, '5 தோலுக்காரன் காடு', '5', '10'),
        (gen_random_uuid()::text, v_route_stage_5, '5 சரவணா ஹோட்டல் பின்புறம்', '5', '10.2'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வைகுந்தம்', '5', '10'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வண்ணங்குட்டை பிரிவு', '5', '9'),
        (gen_random_uuid()::text, v_route_stage_5, '5 குண்டல்பட்டி விநாயகர் கோவில்', '5', '10'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பெருமாகவுண்டன் வளவு', '5', NULL),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஏரிமூலை', '5', '8.85'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கொம்பாடி காடு', '5', '8.5'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கோணபைப்', '5', '8.58'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வெள்ளரி வெள்ளி ரிங் ரோடு', '5', '9.54'),
        (gen_random_uuid()::text, v_route_stage_5, '5 நெசவாளர் காலணி', '5', '8.84'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பெயின்டிங் பட்டறை', '5', '8.46'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வெள்ளரி வெள்ளி பிரிவு-1', '5', '8.34'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வெள்ளரி வெள்ளி பிரிவு-2', '5', '8.34'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஹவுசிங் போர்டு-2', '5', '8.24'),
        (gen_random_uuid()::text, v_route_stage_5, '5 விஸ்டம் பள்ளி', '5', '8.2'),
        (gen_random_uuid()::text, v_route_stage_5, '5 காளியம்மன் கோவில்', '5', '8.1'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஹவுசிங் போர்டு-1', '5', '8.24'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஐயன்காட்டூர்', '5', '9.8'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மாரியம்மன் கோவில்', '5', '9.8'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ராஜாமணித்தோட்டம்', '5', '9.98'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஒருக்காமலை', '5', '8.39'),
        (gen_random_uuid()::text, v_route_stage_5, '5 புதுப்பாளையம் -1', '5', '9.97'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எட்டிக்குட்டைமேடு-1', '5', '9.98'),
        (gen_random_uuid()::text, v_route_stage_5, '5 புதுப்பாளையம்-2', '5', '9.97'),
        (gen_random_uuid()::text, v_route_stage_5, '5 புதுப்பாளையம்-3', '5', '9.97'),
        (gen_random_uuid()::text, v_route_stage_5, '5 புதுப்பாளையம் வாய்க்கால் பாளையம்', '5', '9.71'),
        (gen_random_uuid()::text, v_route_stage_5, '5 புதுப்பாளையம் பெருமாள்கோவில்-1', '5', '9.46'),
        (gen_random_uuid()::text, v_route_stage_5, '5 புதுப்பாளையம் பெருமாள்கோவில்-2', '5', '9.46'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஈஸ்வரன் கோவில்', '5', '8.75'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ராாயணம்பட்டி கரட்டுக்காடு', '5', '8.56'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ராாயணம்பட்டி', '5', '8.77'),
        (gen_random_uuid()::text, v_route_stage_5, '5 சடையம்பாளையம்', '5', '10'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ராாயணம்பட்டி காட்டுவளவு', '5', '8.56'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ராயணம்பட்டி பெரியமாரியம்மன் கோவில்', '5', '9'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பாச்சாலியூர் காட்டுவளவு', '5', '9.5'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பாச்சாலியூர்', '5', '9.5'),
        (gen_random_uuid()::text, v_route_stage_5, '5 தொப்பக்காடு-1', '5', '8.12'),
        (gen_random_uuid()::text, v_route_stage_5, '5 தொப்பக்காடு-2', '5', '8.12'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பச்சியம்மன்கோவில்', '5', '9.25'),
        (gen_random_uuid()::text, v_route_stage_5, '5 காட்டுவளவு-1', '5', '9.75'),
        (gen_random_uuid()::text, v_route_stage_5, '5 காட்டுவளவு-2', '5', '9.75'),
        (gen_random_uuid()::text, v_route_stage_5, '5 புதுக்குடியானூர்', '5', '9.51'),
        (gen_random_uuid()::text, v_route_stage_5, '5 சிவன் கரடு-1', '5', '8.49'),
        (gen_random_uuid()::text, v_route_stage_5, '5 சிவன் கரடு-2', '5', '8.49'),
        (gen_random_uuid()::text, v_route_stage_5, '5 தோப்புக்காடு-1', '5', '9.92'),
        (gen_random_uuid()::text, v_route_stage_5, '5 தோப்புக்காடு-2', '5', '9.92'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கோம்மைக்காடு', '5', '8.08'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எட்டிக்குட்டைமேடு-2', '5', '8.11'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஆலச்சம்பாளையம் ரிங்ரோடு', '5', '9.98'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஆலச்சம்பாளையம்', '5', '9.55'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஆலச்சம்பாளையம் பாறைக்காட்டு மேடு', '5', '9.39'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஏ.டி.சி.டிப்போ', '5', '8.55'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மேட்டுத்தெரு', '5', '8.21'),
        (gen_random_uuid()::text, v_route_stage_5, '5 குஞ்சப்பனூர்', '5', '9.89'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகப்பம்பாளையம் ஆயில் மில்', '5', '9.35'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகப்பம்பாளையம்', '5', '9.17'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகப்பம்பாளையம்-1', '5', '9.17'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகப்பம்பாளையம் -2', '5', '9.17'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகப்பம்பாளையம் -3', '5', '8.79'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கொல்லப்பட்டி கிணறு', '5', '9.8'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கொல்லப்பட்டி-1', '5', '8.6'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கொல்லப்பட்டி-2', '5', '8.5'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கொல்லப்பட்டி-3', '5', '8.4'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கொல்லப்பட்டி-4', '5', '8.3'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கொல்லப்பட்டி ஏரிக்காடு', '5', '9.8'),
        (gen_random_uuid()::text, v_route_stage_5, '5 போஸ்ட் ஆபிஸ்', '5', '8.5'),
        (gen_random_uuid()::text, v_route_stage_5, '5 நாதன்காடு', '5', '9.01'),
        (gen_random_uuid()::text, v_route_stage_5, '5 காளிப்பட்டி பிரிவு -3', '5', '8.59'),
        (gen_random_uuid()::text, v_route_stage_5, '5 காளிப்பட்டி பிரிவு -2`', '5', '8.59'),
        (gen_random_uuid()::text, v_route_stage_5, '5 காளிப்பட்டி பிரிவு -1', '5', '8.59'),
        (gen_random_uuid()::text, v_route_stage_5, '5 செல்லப்பம்பட்டி', '5', '9.95'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வேலாக்கோவில்-4', '5', '8.26'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வேலாக்கோவில்-3', '5', '8.23'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வேலாக்கோவில்-2', '5', '8.21'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வேலாக்கோவில்-1', '5', '8.13'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஏரிக்காடு', '5', '9.27'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மெய்யம்பளையம்-5', '5', '8.26'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மெய்யம்பளையம்-4', '5', '8.48'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மெய்யம்பளையம்-3', '5', '8.58'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மெய்யம்பளையம்-2', '5', '8.88'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மெய்யம்பளையம்-1', '5', '9.15'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வாழக்குட்டை', '5', NULL),
        (gen_random_uuid()::text, v_route_stage_5, '5 குப்பதாசன் வளவு-1', '5', '9.02'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வாளன் வளவு', '5', '8.31'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வேலமாவலசு-2', '5', '10'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அண்ணாமலைக்காடு', '5', '9.7'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பிள்ளையார் கோவில்', '5', '9.5'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கோழிப்பண்ணை', '5', '8'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பாசபாலிக்காடு', '5', '9.2'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பாசபாலிக்காடு முருகன் கோவில்', '5', '9'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பாலதலையான்காடு', '5', '8.4'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கோணமோரி', '5', '8.91'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எலவம்பாளையம் ஊர்', '5', '9.1'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பள்ளிப்பட்டி-1', '5', '8.3'),
        (gen_random_uuid()::text, v_route_stage_5, '5 இலவம்பாளையம்-1', '5', '9'),
        (gen_random_uuid()::text, v_route_stage_5, '5 இலவம்பாளையம் - 2', '5', '8.8'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பள்ளிப்பட்டி -1', '5', '8.46'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பள்ளிப்பட்டி -2', '5', '8.46'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பள்ளிப்பட்டி', '5', '8.46'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஆவணியூர்', '5', '9.24'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கிரேஸி சில்க்ஸ்', '5', '8.64'),
        (gen_random_uuid()::text, v_route_stage_5, '5 P.R.M.பங்க்', '5', '8.37'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மூக்கரை பெருமாள் கோவில்-1', '5', '8.06'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மூக்கரை பெருமாள் கோவில்-2', '5', '8.02'),
        (gen_random_uuid()::text, v_route_stage_5, '5 காளிகவுண்டன்வளவு', '5', '9.39'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மோட்டூர் பிரிவு', '5', '8.51'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எடப்பாடி-ஹவுசிங்போர்டு-1', '5', '8.26'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எடப்பாடி-ஹவுசிங்போர்டு-2', '5', '8.34'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எடப்பாடி-ஹவுசிங்போர்டு-3', '5', '8.34'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எடப்பாடி-ஹவுசிங்போர்டு-4', '5', '8.48'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எடப்பாடி-ஹவுசிங்போர்டு-5', '5', '8.56'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எடப்பாடி-ஹவுசிங்போர்டு-6', '5', '8.67'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எடப்பாடி-ஹவுசிங்போர்டு-7', '5', '8.67'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பனஞ்சாரி', '5', NULL),
        (gen_random_uuid()::text, v_route_stage_5, '5 காட்டூர் ரோடு', '5', NULL),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஏரி ரோடு', '5', '8.58'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஏரி ரோடு-1', '5', '8.58'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கன்னியாம்பட்டி', '5', '9.53'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பாச்சலியூர் பிரிவு சமுதாயக்கூடம்', '5', '9.15'),
        (gen_random_uuid()::text, v_route_stage_5, '5 சிவன்கரடு', '5', '8.45'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கோணங்கியூர்-4', '5', '9.49'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கோணங்கியூர்-3', '5', '9.49'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கோணங்கியூர்-2', '5', '9.49'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கோணங்கியூர்-1', '5', '9.49'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகப்பம்பாளையம் புதூர்-1', '5', '9.63'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகப்பம்பாளையம் புதூர்-2', '5', '9.63'),
        (gen_random_uuid()::text, v_route_stage_5, '5 KVS ஆயில் மில்', '5', '9.13'),
        (gen_random_uuid()::text, v_route_stage_5, '5 போர்வல் ஸ்டாப்-1', '5', '8.51'),
        (gen_random_uuid()::text, v_route_stage_5, '5 போர்வல் ஸ்டாப்-2', '5', '8.13'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வடக்கத்தியங்காடு', '5', NULL),
        (gen_random_uuid()::text, v_route_stage_5, '5 காளிப்பட்டி பிரிவு ரோடு', '5', '8.46'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கோரணம்பட்டி', '5', '8.21'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வேலாயுதக்கரடு', '5', '9.83'),
        (gen_random_uuid()::text, v_route_stage_5, '5 சிவன்கோவில்', '5', '9.83'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மேட்டுப்பாளையம் பஸ்ஸ்டாப்', '5', '9.58'),
        (gen_random_uuid()::text, v_route_stage_5, '5 செக்குமேடு', '5', '9.19'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எட்டிக்குட்டைமேடு', '5', '8.22'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எட்டிக்குட்டைமேடு-4', '5', '8.22'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பருப்பு மில்', '5', '8.14'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எலவம்பாளையம்', '5', '9.02'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஆலச்சம்பாளையம் - 1', '5', '9.55'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஆலச்சம்பாளையம் - 2', '5', '9.55'),
        (gen_random_uuid()::text, v_route_stage_5, '5 மோட்டூர் காட்டு வளவு', '5', '9.58'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அழகனூர்', '5', '9.05'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஆசாரிப்பட்டறை', '5', '8.67'),
        (gen_random_uuid()::text, v_route_stage_5, '5 அண்ணாநகர்-2', '5', '8.09'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஆவணியூர்-1', '5', '9.2'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஆவணியூர்-2', '5', '9.2'),
        (gen_random_uuid()::text, v_route_stage_5, '5 PRM பங்க்', '5', '8.2'),
        (gen_random_uuid()::text, v_route_stage_5, '5 பாலத்தலையாங்காடு', '5', '9.7'),
        (gen_random_uuid()::text, v_route_stage_5, '5 வண்டித்தடம்', '5', '8.3'),
        (gen_random_uuid()::text, v_route_stage_5, '5 ஆச்சார்யா பள்ளி', '5', '9.9 Km'),
        (gen_random_uuid()::text, v_route_stage_5, '5 கோணபைப்-1', '5', '8.7 Km'),
        (gen_random_uuid()::text, v_route_stage_5, '5 எடப்பாடி-ஹவுசிங் போர்டு', '5', '8 Km'),
        (gen_random_uuid()::text, v_route_stage_6, '6 பாட்டப்பன்கோவில்', '6', '11.7'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மகுடஞ்சாவடி-1', '6', '10.7'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மகுடஞ்சாவடி-2', '6', '10.4'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மகுடஞ்சாவடி-3', '6', '10'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மணியங்கரான் காடு', '6', '11'),
        (gen_random_uuid()::text, v_route_stage_6, '6 கணக்கச்சிப்பாளையம்', '6', '11'),
        (gen_random_uuid()::text, v_route_stage_6, '6 ஊஞ்சக்காடு-1', '6', '11.05'),
        (gen_random_uuid()::text, v_route_stage_6, '6 ஊஞ்சக்காடு-2', '6', '11.05'),
        (gen_random_uuid()::text, v_route_stage_6, '6 ஊஞ்சக்காடு-3', '6', '11.05'),
        (gen_random_uuid()::text, v_route_stage_6, '6 ஊஞ்சக்காடு-4', '6', '11.05'),
        (gen_random_uuid()::text, v_route_stage_6, '6 ஊஞ்சக்காடு-5', '6', '11.05'),
        (gen_random_uuid()::text, v_route_stage_6, '6 சுண்டாக்கல்-1', '6', '11.81'),
        (gen_random_uuid()::text, v_route_stage_6, '6 சுண்டாக்கல்-2', '6', '11.81'),
        (gen_random_uuid()::text, v_route_stage_6, '6 கரடு-1', '6', '11.81'),
        (gen_random_uuid()::text, v_route_stage_6, '6 கரடு-2', '6', '11.81'),
        (gen_random_uuid()::text, v_route_stage_6, '6 கரடு-3', '6', '11.81'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மாரியம்மன் கோவில்', '6', '11.9'),
        (gen_random_uuid()::text, v_route_stage_6, '6 சங்ககிரி ஆர்.கே.நகர்', '6', '11.8'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மாவிலிப்பாளையம்', '6', '11.2'),
        (gen_random_uuid()::text, v_route_stage_6, '6 கொங்கணாபுரம் பிரிவு ரோடு', '6', '10.5'),
        (gen_random_uuid()::text, v_route_stage_6, '6 சமுத்திரம்-1', '6', '11.14'),
        (gen_random_uuid()::text, v_route_stage_6, '6 சமுத்திரம்-2', '6', '11.14'),
        (gen_random_uuid()::text, v_route_stage_6, '6 சமுத்திரம்-3', '6', '11.11'),
        (gen_random_uuid()::text, v_route_stage_6, '6 சமுத்திரம்-4', '6', '11.07'),
        (gen_random_uuid()::text, v_route_stage_6, '6 சமுத்திரம்-5', '6', '11.07'),
        (gen_random_uuid()::text, v_route_stage_6, '6 முத்தையம்பட்டி அரசுபள்ளி', '6', '11.39'),
        (gen_random_uuid()::text, v_route_stage_6, '6 முத்தையம்பட்டி', '6', '11.84'),
        (gen_random_uuid()::text, v_route_stage_6, '6 காட்டூர்', '6', '11.04'),
        (gen_random_uuid()::text, v_route_stage_6, '6 கரும்பாலை', '6', '11.01'),
        (gen_random_uuid()::text, v_route_stage_6, '6 புதுப்பாளையம் சந்தை', '6', '10.08'),
        (gen_random_uuid()::text, v_route_stage_6, '6 புதுப்பாளையம் மெடிக்கல்', '6', '10.03'),
        (gen_random_uuid()::text, v_route_stage_6, '6 கன்னியாம்பட்டி காட்டுவளவு', '6', '11.2'),
        (gen_random_uuid()::text, v_route_stage_6, '6 கண்ணியாம்பட்டி', '6', '11.2'),
        (gen_random_uuid()::text, v_route_stage_6, '6 காளியம்மன் கோவில்', '6', '11.2'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மூலக்கடை-1', '6', '10.7'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மூலக்கடை-2', '6', '10.7'),
        (gen_random_uuid()::text, v_route_stage_6, '6 பணங்காடு', '6', '10.2'),
        (gen_random_uuid()::text, v_route_stage_6, '6 செக்குமேடு', '6', '10.02'),
        (gen_random_uuid()::text, v_route_stage_6, '6 அக்கரைப்பட்டி-1', '6', '11.02'),
        (gen_random_uuid()::text, v_route_stage_6, '6 அக்கரைப்பட்டி-2', '6', '11.02'),
        (gen_random_uuid()::text, v_route_stage_6, '6 அக்கரைப்பட்டி-3', '6', '11.02'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மூலப்பாதை (கல்வடங்கம்)', '6', '11.07'),
        (gen_random_uuid()::text, v_route_stage_6, '6 அருவங்காட்டூர்-1', '6', '11.08'),
        (gen_random_uuid()::text, v_route_stage_6, '6 அருவங்காட்டூர்-2', '6', '11.08'),
        (gen_random_uuid()::text, v_route_stage_6, '6 புதூர் மூலக்கடை', '6', '11.03'),
        (gen_random_uuid()::text, v_route_stage_6, '6 புதூர்', '6', '11.01'),
        (gen_random_uuid()::text, v_route_stage_6, '6 நாடார் காலணி-1', '6', '11.1'),
        (gen_random_uuid()::text, v_route_stage_6, '6 நாடார் காலணி-2', '6', '11'),
        (gen_random_uuid()::text, v_route_stage_6, '6 வேலமாவலசு-1', '6', '10.3'),
        (gen_random_uuid()::text, v_route_stage_6, '6 பாண்டியமேடு', '6', '10.1'),
        (gen_random_uuid()::text, v_route_stage_6, '6 ஆலங்கொட்டாய்-1', '6', '12'),
        (gen_random_uuid()::text, v_route_stage_6, '6 ஆலங்கொட்டாய்-2', '6', '12'),
        (gen_random_uuid()::text, v_route_stage_6, '6 எட்டிக்குட்டைமேடு-1', '6', '10'),
        (gen_random_uuid()::text, v_route_stage_6, '6 எட்டிக்குட்டைமேடு-2', '6', '10'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மகுடஞ்சாவடி கோயில்', '6', '11.5'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மகுடஞ்சாவடி', '6', '11'),
        (gen_random_uuid()::text, v_route_stage_6, '5 ஆலக்கொட்டாய்', '6', '10.82'),
        (gen_random_uuid()::text, v_route_stage_6, '6 ஏகாபுரம்-2', '6', '10.72'),
        (gen_random_uuid()::text, v_route_stage_6, '6 ஏகாபுரம்-1', '6', '10.72'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மோட்டூர்', '6', '11.07'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மோட்டூர்-2', '6', '11.07'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மோட்டூர்-1', '6', '11.07'),
        (gen_random_uuid()::text, v_route_stage_6, '6 கூத்தம்பாளையம்', '6', '11.08'),
        (gen_random_uuid()::text, v_route_stage_6, '6 அருவங்காட்டூர்', '6', '11.01'),
        (gen_random_uuid()::text, v_route_stage_6, '6 புதுப்பாளையம்', '6', '11.59'),
        (gen_random_uuid()::text, v_route_stage_6, '6 பனங்காட்டூர்-1', '6', '10.08'),
        (gen_random_uuid()::text, v_route_stage_6, '6 பனங்காட்டூர்-2', '6', '10.08'),
        (gen_random_uuid()::text, v_route_stage_6, '6 குள்ளம்பட்டி', '6', '11.09'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மகுடஞ்சாவடி -1', '6', '11.04'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மகுடஞ்சாவடி அரசு பள்ளி', '6', '10.05'),
        (gen_random_uuid()::text, v_route_stage_6, '6 குப்பாண்டி பாளையம்-1', '6', '10.01'),
        (gen_random_uuid()::text, v_route_stage_6, '6 குப்பாண்டி பாளையம்-2', '6', '10.01'),
        (gen_random_uuid()::text, v_route_stage_6, '6 வெள்ளநாய்க்கன்பாளையம்', '6', '10.2'),
        (gen_random_uuid()::text, v_route_stage_6, 'வாள அங்காளம்மன் கோவில்', '6', '11.3'),
        (gen_random_uuid()::text, v_route_stage_6, '6 சுண்ணாம்புகுட்டை', '6', '11.9'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மலையனூர்', '6', '10.5'),
        (gen_random_uuid()::text, v_route_stage_6, '6 மாரிமுத்தான்', '6', '11.1'),
        (gen_random_uuid()::text, v_route_stage_6, '6 நாடார் காலணி', '6', '11.9'),
        (gen_random_uuid()::text, v_route_stage_6, '6 நெட்ட பெருமாள் காடு', '6', '10.2'),
        (gen_random_uuid()::text, v_route_stage_6, '6 சங்ககிரி எஸ்.கே. நகர்', '6', '11.8 Km'),
        (gen_random_uuid()::text, v_route_stage_6, '6 கள்ளுக்கடை-1', '6', '11.3 Km'),
        (gen_random_uuid()::text, v_route_stage_6, '6 கள்ளுக்கடை-2', '6', '11.3 Km'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கௌதம் மெடிக்கல்', '7', '13.5'),
        (gen_random_uuid()::text, v_route_stage_7, '7 சந்தைப்பேட்டை', '7', '13.8'),
        (gen_random_uuid()::text, v_route_stage_7, '7 ஃபயர் சர்வீஸ்', '7', '12.4'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கிருஷ்ணா நகர்', '7', '12.7'),
        (gen_random_uuid()::text, v_route_stage_7, '7 முனியப்பன்கோவில்-2', '7', '13.26'),
        (gen_random_uuid()::text, v_route_stage_7, '7 பூசாரிவளவு', '7', '13.92'),
        (gen_random_uuid()::text, v_route_stage_7, '7 பனிக்கனூர் மூலக்கடை', '7', '13.12'),
        (gen_random_uuid()::text, v_route_stage_7, '7 பனிக்கனூர்', '7', '12.66'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மன்மதன் வளவு', '7', '13.08'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கசப்பேரி', '7', '13.11'),
        (gen_random_uuid()::text, v_route_stage_7, '7 பனஞ்சாரி', '7', '13.08'),
        (gen_random_uuid()::text, v_route_stage_7, '7 ஓடக்காடு', '7', '13.02'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கனரா வங்கி', '7', '12.04'),
        (gen_random_uuid()::text, v_route_stage_7, '7 சின்னப்பம்பட்டி', '7', '12.02'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மேட்டுப்பாளையம்-1', '7', '13.9'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மேட்டுப்பாளையம்-2', '7', '13.8'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மேட்டுப்பாளையம்-3', '7', '13.2'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மேட்டுப்பாளையம்-4', '7', '13.1'),
        (gen_random_uuid()::text, v_route_stage_7, '7 குள்ளம்பட்டி', '7', '12.09'),
        (gen_random_uuid()::text, v_route_stage_7, '7 பாரதிநகர்', '7', '12.05'),
        (gen_random_uuid()::text, v_route_stage_7, '7 செங்கானூர்', '7', '13.8'),
        (gen_random_uuid()::text, v_route_stage_7, '7 சக்தி வேபிரிட்ஜ்', '7', '12.03'),
        (gen_random_uuid()::text, v_route_stage_7, '7 அத்தனூர்', '7', '13.08'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மேட்டுக்காடு-1', '7', '13.03'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மேட்டுக்காடு-2', '7', '13.03'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மேட்டுக்காடு-3', '7', '13.03'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மேட்டுக்காடு-4', '7', '13.01'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மேட்டுக்காடு-5', '7', '13.01'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மேட்டுக்காடு-6', '7', '13.01'),
        (gen_random_uuid()::text, v_route_stage_7, '7 காச்சக்காரனூர்', '7', '12.06'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கூத்தம்பாளையம்-1', '7', '12.04'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கூத்தம்பாளையம்-2', '7', '12.04'),
        (gen_random_uuid()::text, v_route_stage_7, '7 பொன்னியங்கோவில்', '7', '12.02'),
        (gen_random_uuid()::text, v_route_stage_7, '7 பறையங்காட்டானூர்', '7', '13'),
        (gen_random_uuid()::text, v_route_stage_7, '7 வளையசெட்டிப்பட்டி பஸ் ஸ்டாப்', '7', '13.6'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கலியகவுண்டனூர்-1', '7', '13.98'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கலியகவுண்டனூர்-2', '7', '13.98'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கலியகவுண்டனூர்-3', '7', '13.8'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கலியகவுண்டனூர்-4', '7', '13.5'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கலியகவுண்டனூர்-5', '7', '13.5'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மோட்டூர்', '7', '13'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மோட்டூர் பிரிவு', '7', '12.8'),
        (gen_random_uuid()::text, v_route_stage_7, '7 ஏகாபுரம்', '7', '12.6'),
        (gen_random_uuid()::text, v_route_stage_7, '7 ஏகாபுரம்-1', '7', '12.6'),
        (gen_random_uuid()::text, v_route_stage_7, '7 காக்காபாளையம்', '7', '13.3'),
        (gen_random_uuid()::text, v_route_stage_7, '7 R.K. தோப்பு', '7', '13'),
        (gen_random_uuid()::text, v_route_stage_7, '7 வடுகப்பட்டி', '7', '13.08'),
        (gen_random_uuid()::text, v_route_stage_7, '7 கலியகவுண்டனூர்', '7', '12.05'),
        (gen_random_uuid()::text, v_route_stage_7, '7 சமுத்திரம்', '7', '13.03'),
        (gen_random_uuid()::text, v_route_stage_7, '7 சின்னப்பம்பட்டி -2', '7', '12.03'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மூலப்பாதை எடைநிலையம்', '7', '12.02'),
        (gen_random_uuid()::text, v_route_stage_7, '7 வாய்க்கால் பாலம்', '7', '12.09'),
        (gen_random_uuid()::text, v_route_stage_7, '7 காகாபாளையம்', '7', '13.98'),
        (gen_random_uuid()::text, v_route_stage_7, '7 மஞ்சகல்பட்டி', '7', '13.9'),
        (gen_random_uuid()::text, v_route_stage_7, '7 எபினேசர் காலனி', '7', '13.8 Km'),
        (gen_random_uuid()::text, v_route_stage_7, '7 டி.பி. ரோடு', '7', '14 Km'),
        (gen_random_uuid()::text, v_route_stage_7, '7 திரு ஸ்டுடியோ', '7', '13.8 Km'),
        (gen_random_uuid()::text, v_route_stage_7, '7 சங்ககிரி சந்தைப்பேட்டை', '7', '13.2'),
        (gen_random_uuid()::text, v_route_stage_7, '7 வெள்ளக்கவுண்டனூர்', '7', '13 Km'),
        (gen_random_uuid()::text, v_route_stage_7, '7 அமலா பள்ளி-1', '7', '12 Km'),
        (gen_random_uuid()::text, v_route_stage_7, '7 அமலா பள்ளி-2', '7', '12 Km'),
        (gen_random_uuid()::text, v_route_stage_8, '8 தாசங்காடு', '8', '14.8'),
        (gen_random_uuid()::text, v_route_stage_8, '8 ஆசிரியர் காலனி', '8', '14.08'),
        (gen_random_uuid()::text, v_route_stage_8, '8 முனியம்பட்டி ரைஸ்மில்', '8', '14.74'),
        (gen_random_uuid()::text, v_route_stage_8, '8 தாடிக்காரன்பட்டி', '8', '14.08'),
        (gen_random_uuid()::text, v_route_stage_8, '8 மடத்தூர்', '8', '14.02'),
        (gen_random_uuid()::text, v_route_stage_8, '8 செட்டிப்பட்டி சந்தை', '8', '15.01'),
        (gen_random_uuid()::text, v_route_stage_8, '8 பொன்னம்பாளையம்', '8', '15.8'),
        (gen_random_uuid()::text, v_route_stage_8, '8 காவனூர்', '8', '15.8'),
        (gen_random_uuid()::text, v_route_stage_8, '8 பூமணியூர்', '8', '15.4'),
        (gen_random_uuid()::text, v_route_stage_8, '8 பூச்சிமரத்துக்காடு', '8', '15.8'),
        (gen_random_uuid()::text, v_route_stage_8, '8 பூமணியூர் ஸ்கூல்', '8', '15.08'),
        (gen_random_uuid()::text, v_route_stage_8, '8 ஒக்கிலிப்பட்டி', '8', '15.06'),
        (gen_random_uuid()::text, v_route_stage_8, '8 எட்டிக்குட்டைமேடு (கல்வடங்கம்)', '8', '15.04'),
        (gen_random_uuid()::text, v_route_stage_8, '8 தண்ணீர்தாசனூர்', '8', '15.01'),
        (gen_random_uuid()::text, v_route_stage_8, '8 அய்யனூர்', '8', '15.08'),
        (gen_random_uuid()::text, v_route_stage_8, '8 தாடிக்காரனூர்-1', '8', '14.09'),
        (gen_random_uuid()::text, v_route_stage_8, '8 தாடிக்காரனூர்-2', '8', '14.08'),
        (gen_random_uuid()::text, v_route_stage_8, '8 தப்பக்குட்டை பிரிவு', '8', '15.09'),
        (gen_random_uuid()::text, v_route_stage_8, '8 குப்பதாசன்வளவு', '8', '15'),
        (gen_random_uuid()::text, v_route_stage_8, '8 கூலக்கண்ணன் காடு', '8', '14..8'),
        (gen_random_uuid()::text, v_route_stage_8, '8 வளையசெட்டிப்பட்டி பிரிவு', '8', '15'),
        (gen_random_uuid()::text, v_route_stage_8, '8 வேம்படிதாளம் பாலம்', '8', '15'),
        (gen_random_uuid()::text, v_route_stage_8, '8 கவுண்டனேரி-1', '8', '15.07'),
        (gen_random_uuid()::text, v_route_stage_8, '8 அத்தனூர்', '8', '15.01'),
        (gen_random_uuid()::text, v_route_stage_8, '8 தாடிக்காரனூர்', '8', '15.06'),
        (gen_random_uuid()::text, v_route_stage_8, '8 மேட்டுக்காடு', '8', '14.01'),
        (gen_random_uuid()::text, v_route_stage_8, '8 மேட்டுக்காடு விநாயகர் கோவில்', '8', '14.04'),
        (gen_random_uuid()::text, v_route_stage_8, '8 பனிக்கனுர்', '8', '15.03'),
        (gen_random_uuid()::text, v_route_stage_8, '8 முனியம்பட்டி', '8', '15.98'),
        (gen_random_uuid()::text, v_route_stage_8, '8 முனியப்பன் கோவில்', '8', '15.98'),
        (gen_random_uuid()::text, v_route_stage_8, '8 வேம்படிதாளம்', '8', '15.08'),
        (gen_random_uuid()::text, v_route_stage_8, '8 பனங்காடு', '8', NULL),
        (gen_random_uuid()::text, v_route_stage_8, '8 செட்டிமாங்குறிச்சி', '8', '13.6'),
        (gen_random_uuid()::text, v_route_stage_8, '8 ரெயின்போ காலனி', '8', '15.2 Km'),
        (gen_random_uuid()::text, v_route_stage_8, '8 கொங்கு நகர்', '8', '14.6 Km'),
        (gen_random_uuid()::text, v_route_stage_8, '8 பில்லுக்குறிச்சி', '8', '14.5 Km'),
        (gen_random_uuid()::text, v_route_stage_8, '8 பில்லுக்குறிச்சி வே பிரிட்ஜ்', '8', '14.3'),
        (gen_random_uuid()::text, v_route_stage_9, '9 மயிலம்பட்டி', '9', '20.02'),
        (gen_random_uuid()::text, v_route_stage_9, '9 கொட்டாயூர்', '9', '17.08'),
        (gen_random_uuid()::text, v_route_stage_9, '9 கல்வடங்கம்', '9', '18.04'),
        (gen_random_uuid()::text, v_route_stage_9, '9 இளம்பிள்ளை-கறிக்கடை', '9', '18'),
        (gen_random_uuid()::text, v_route_stage_9, '9 புளியம்பட்டி', '9', '20.2'),
        (gen_random_uuid()::text, v_route_stage_9, '9 இளம்பிள்ளை நான்கு ரோடு', '9', '19.9'),
        (gen_random_uuid()::text, v_route_stage_9, '9 இளம்பிள்ளை', '9', '19.9'),
        (gen_random_uuid()::text, v_route_stage_9, '9 இளம்பிள்ளை ராதா மெடிக்கல்ஸ்', '9', '20.2'),
        (gen_random_uuid()::text, v_route_stage_9, '9 ராஜன் கண் மருத்துவமனை', '9', '19.6'),
        (gen_random_uuid()::text, v_route_stage_9, '9 இளம்பிள்ளை ஏரிக்கரை', '9', '19.2'),
        (gen_random_uuid()::text, v_route_stage_9, '9 வாரி பேக்கரி', '9', '19.2'),
        (gen_random_uuid()::text, v_route_stage_9, '9 ராமாபுரம்', '9', '19.5'),
        (gen_random_uuid()::text, v_route_stage_9, '9 மண்கரடு பிரிவு', '9', '19.2'),
        (gen_random_uuid()::text, v_route_stage_9, '9 பெருமாகவுண்டம்பட்டி', '9', '18.6'),
        (gen_random_uuid()::text, v_route_stage_9, '9 வேம்படிதாளம்', '9', '17.8'),
        (gen_random_uuid()::text, v_route_stage_9, '9 பெருமாகவுண்டம்பட்டி-3', '9', '18.6'),
        (gen_random_uuid()::text, v_route_stage_9, '9 பாட்டப்பன் நகர்', '9', '17.01'),
        (gen_random_uuid()::text, v_route_stage_9, '9 தேவூர்', '9', '19.08'),
        (gen_random_uuid()::text, v_route_stage_9, '9 செட்டிப்பட்டி', '9', '16.05'),
        (gen_random_uuid()::text, v_route_stage_9, '9 கரையானூர் பிரிவு', '9', '16.01'),
        (gen_random_uuid()::text, v_route_stage_9, '9 ராதா மெடிக்கல்ஸ்', '9', '20.06'),
        (gen_random_uuid()::text, v_route_stage_9, '9 சந்தைப்பேட்டை', '9', '19.05'),
        (gen_random_uuid()::text, v_route_stage_9, '9 பெருமாகவுண்டம்பட்டி ஹைஸ்கூல்', '9', '18.07'),
        (gen_random_uuid()::text, v_route_stage_9, '9 ஜலகண்டாபுரம்', '9', '20.4'),
        (gen_random_uuid()::text, v_route_stage_9, '9 கட்டிநாய்க்கன்பட்டி', '9', '19.5'),
        (gen_random_uuid()::text, v_route_stage_9, '9 குருக்குப்பட்டி', '9', '18.1'),
        (gen_random_uuid()::text, v_route_stage_9, '9 சக்தி நகர்', '9', '17.4 Km'),
        (gen_random_uuid()::text, v_route_stage_9, '9 பூலாம்பட்டி பங்', '9', '18.4'),
        (gen_random_uuid()::text, v_route_stage_9, '9 காட்டூர்-1', '9', '18.4'),
        (gen_random_uuid()::text, v_route_stage_9, '9 காட்டூர்-2', '9', '18.4')
    ON CONFLICT DO NOTHING;
END $$;
